<a href="https://colab.research.google.com/github/Voyageran/StartNN/blob/main/Pytorch_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
from google.colab import drive
drive.mount('/content/gdrive')
sys.path.insert(0,"/content/content/notebooks/colabInstallPackage")

!cp -av '/content/gdrive/MyDrive/Colab Notebooks/d2l' '/content/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
'/content/gdrive/MyDrive/Colab Notebooks/d2l/paddle.py' -> '/content/d2l/paddle.py'
'/content/gdrive/MyDrive/Colab Notebooks/d2l/mxnet.py' -> '/content/d2l/mxnet.py'
'/content/gdrive/MyDrive/Colab Notebooks/d2l/tensorflow.py' -> '/content/d2l/tensorflow.py'
'/content/gdrive/MyDrive/Colab Notebooks/d2l/torch.py' -> '/content/d2l/torch.py'
'/content/gdrive/MyDrive/Colab Notebooks/d2l/__init__.py' -> '/content/d2l/__init__.py'
'/content/gdrive/MyDrive/Colab Notebooks/d2l/__pycache__/mxnet.cpython-310.pyc' -> '/content/d2l/__pycache__/mxnet.cpython-310.pyc'
'/content/gdrive/MyDrive/Colab Notebooks/d2l/__pycache__/__init__.cpython-310.pyc' -> '/content/d2l/__pycache__/__init__.cpython-310.pyc'
'/content/gdrive/MyDrive/Colab Notebooks/d2l/__pycache__/torch.cpython-310.pyc' -> '/content/d2l/__pycache__/torch.cpython-310.pyc'
'/content/gdrive/MyDrive/Colab Notebook

# **Layers and Modules**


In [ ]:
import torch
from torch import nn
from torch.nn import functional as F #

# Simple single NN
net = nn.Sequential(nn.Linear(20,256), nn.ReLU(), nn.Linear(256, 10))

X = torch.rand(2,20)
net(X).shape #outputs

torch.Size([2, 10])

**自定义块**

任何一个层和一个神经网络都是Module的一个subclass。

Define a class MLP which is the subclass of `nn.Module`

In [ ]:
class MLP(nn.Module):
  def __init__(self):
    super().__init__() # Review inherent
    self.hidden = nn.Linear(20,256)
    self.out = nn.Linear(256, 10)

  def forward(self, X):
    return self.out(F.relu(self.hidden(X)))

In [ ]:
#instantiate
net = MLP()
net(X)  # == net.forward(X)

tensor([[ 0.2917,  0.0283, -0.3037,  0.1345, -0.2363, -0.0971,  0.2100,  0.1017,
          0.1113, -0.3179],
        [ 0.2103,  0.0192, -0.2455,  0.1382, -0.1039,  0.0098, -0.0248,  0.1356,
          0.0627, -0.1701]], grad_fn=<AddmmBackward0>)

In [ ]:
X.shape, net(X).shape, net.forward(X).shape

(torch.Size([2, 20]), torch.Size([2, 10]), torch.Size([2, 10]))

In [ ]:
# 试一下nnSequential
class MySequential(nn.Module):
  def __init__(self, *args):
    super().__init__()
    for block in args: #add layers, as keys
      self._modules[str(block)] = block #ordered dict, insert by order

  def forward(self, X):
    for block in self._modules.values(): #values返回的list跟插入进去返回的顺序一样
      X = block(X) #values里面的keys
    return X

In [ ]:
net = MySequential(nn.Linear(20,256), nn.ReLU(), nn.Linear(256, 10))

In [ ]:
print(net.forward(X))

tensor([[-0.0211,  0.1789,  0.0505,  0.2012,  0.0369,  0.1904,  0.0514, -0.0115,
          0.1747, -0.0095],
        [-0.0809,  0.0909,  0.1927,  0.0850, -0.2080,  0.1496,  0.0335, -0.0416,
          0.2090, -0.0328]], grad_fn=<AddmmBackward0>)


In [ ]:
net = MySequential(nn.Linear(20,256), nn.ReLU(), nn.Linear(256, 10))
net(X)

tensor([[ 0.0420, -0.0817,  0.0341, -0.0889,  0.1902, -0.1443,  0.0811, -0.0778,
          0.0302,  0.2398],
        [-0.0157, -0.1873,  0.0423,  0.0459,  0.0532,  0.0789,  0.0298, -0.1673,
         -0.1093,  0.1977]], grad_fn=<AddmmBackward0>)